# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 621, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.convertButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.convertButton.setObjectName("convertButton")
        self.gridLayout.addWidget(self.convertButton, 5, 1, 1, 3)
        self.pathEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout.addWidget(self.pathEdit, 2, 1, 1, 2)
        self.filterEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.filterEdit.setObjectName("filterEdit")
        self.gridLayout.addWidget(self.filterEdit, 3, 1, 1, 1)
        self.formatEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.formatEdit.setObjectName("formatEdit")
        self.gridLayout.addWidget(self.formatEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.separatorEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.separatorEdit.setObjectName("separatorEdit")
        self.gridLayout.addWidget(self.separatorEdit, 3, 3, 1, 1)
        self.folderPicker = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.folderPicker.setObjectName("folderPicker")
        self.gridLayout.addWidget(self.folderPicker, 2, 3, 1, 1)
        self.deleteChackBox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.deleteChackBox.setWhatsThis("")
        self.deleteChackBox.setObjectName("deleteChackBox")
        self.gridLayout.addWidget(self.deleteChackBox, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pwdEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.pwdEdit.setObjectName("pwdEdit")
        self.gridLayout.addWidget(self.pwdEdit, 1, 1, 1, 2)
        self.pwdPicker = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pwdPicker.setObjectName("pwdPicker")
        self.gridLayout.addWidget(self.pwdPicker, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImgC - gui"))
        self.label_5.setText(_translate("MainWindow", "Separator"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.pathEdit.setToolTip(_translate("MainWindow", "Where do you want the files to be saved after conversion"))
        self.pathEdit.setText(_translate("MainWindow", "."))
        self.filterEdit.setToolTip(_translate("MainWindow", "What type of files do you want to convert"))
        self.filterEdit.setPlaceholderText(_translate("MainWindow", "ex. jpg,png,bmp"))
        self.formatEdit.setToolTip(_translate("MainWindow", "What format do you want to convert the files to"))
        self.formatEdit.setPlaceholderText(_translate("MainWindow", "ex. jpg"))
        self.label_3.setText(_translate("MainWindow", "Output format"))
        self.label_2.setText(_translate("MainWindow", "Filter"))
        self.label_4.setText(_translate("MainWindow", "Destination directory"))
        self.separatorEdit.setToolTip(_translate("MainWindow", "What did you use to separate the filters"))
        self.separatorEdit.setText(_translate("MainWindow", ","))
        self.folderPicker.setText(_translate("MainWindow", "Choose folder"))
        self.deleteChackBox.setToolTip(_translate("MainWindow", "Delete the files after they have been converted?"))
        self.deleteChackBox.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Source directory"))
        self.pwdEdit.setToolTip(_translate("MainWindow", "Where do you want the files to be saved after conversion"))
        self.pwdEdit.setText(_translate("MainWindow", "."))
        self.pwdPicker.setText(_translate("MainWindow", "Choose folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
